### ISSUE TITLE
Unable to Get kmutex v2

### ISSUE THREAD

**Issue by zbysir** [im7mortal/kmutex#8]
If I use go get github.com/im7mortal/kmutex to get this repository, Go will download tag v1.0.1 (the maximum version of major version 1.0).

This version has a deadlock bug, which is fixed in this pull request: https://github.com/im7mortal/kmutex/pull/5, but it is in version v2.0.1.

Then I tried to use go get github.com/im7mortal/kmutex@v2.0.1 to get the latest version, but I received an error:
```
go: github.com/im7mortal/kmutex@v2.0.1: invalid version: module contains a go.mod file, so module path must match major version ("github.com/im7mortal/kmutex/v2")
```
Can you follow this guide to fix it in your free time? https://go.dev/blog/v2-go-modules.

Thank u.

**Comment by im7mortal** [comment]
Thank you @zbysir !!!

I don't understand how it worked before. (Probably it didn't) and how nobody noted it. 

```
$ go get github.com/im7mortal/kmutex/v2@v2.0.1
go: github.com/im7mortal/kmutex@v2.0.1: invalid version: module contains a go.mod file, so module path must match major version ("github.com/im7mortal/kmutex/v2")
$ go get github.com/im7mortal/kmutex/v2@v2.0.2
go: downloading github.com/im7mortal/kmutex/v2 v2.0.2
go: added github.com/im7mortal/kmutex/v2 v2.0.2
$
```


I need to figure out if I should do force push for tag v2.0.0 and v2.0.1 , because probably nobody even could reach these versions.

I am trying to deduct why I even had v2. I think because I changed license to MIT(?). 

I will try to figure out it over weekends


Thank you so much!

**Comment by sepnotican** [comment]
I just used 'go get' with ceritain commit so it worked to me. Tags much better though.

**Comment by zbysir** [comment]
Now, `go get github.com/im7mortal/kmutex/v2` works; it will download version v2.0.2.

Thank you @im7mortal , and thanks to this repository; it is very useful for me.
